[package]
name = "zed-browser"
version = "1.0.0"
description = "A modern, lightweight browser with customizable engine selection"
authors = [""]
license = "MIT"
repository = ""
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.6.0", features = [] }

[dependencies]
tauri = { version = "1.6.0", features = [ "window-set-focus", "window-set-fullscreen", "window-unminimize", "window-close", "window-set-size", "window-hide", "window-maximize", "window-start-dragging", "window-unmaximize", "window-set-position", "http-all", "window-minimize", "window-show", "window-set-title", "shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
